backend:
  name: git-gateway
  branch: main

media_folder: "public/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "sofas"
    label: "Sofas"
    folder: "content/sofas"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "sofas"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Media", name: "media", widget: "list", field: {label: "File", name: "file", widget: "file"}}

  - name: "seats"
    label: "Seats"
    folder: "content/seats"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "seats"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Media", name: "media", widget: "list", field: {label: "File", name: "file", widget: "file"}}

  - name: "sets"
    label: "Sets"
    folder: "content/sets"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "sets"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Media", name: "media", widget: "list", field: {label: "File", name: "file", widget: "file"}}

  - name: "tables"
    label: "Tables"
    folder: "content/tables"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "tables"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Media", name: "media", widget: "list", field: {label: "File", name: "file", widget: "file"}}

  - name: "changing_screen"
    label: "Changing Screen"
    folder: "content/changing_screen"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "changing_screen"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Media", name: "media", widget: "list", field: {label: "File", name: "file", widget: "file"}}

  - name: "swings"
    label: "Swings"
    folder: "content/swings"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Category", name: "category", widget: "hidden", default: "swings"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Media", name: "media", widget: "list", field: {label: "File", name: "file", widget: "file"}}
